version: '3.9'

services:
  beer-club-colombia-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beer-club-colombia-ui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

    networks:
      - beer-club-colombia-network

networks:
  beer-club-colombia-network:
    driver: bridge
